### ISSUE TITLE
cant find dependencies

### ISSUE THREAD

**Issue by Wdboyes13** [Ubuntufanboy/bad-apple#22]
im on macos zsh and managed to install all the dependencies but when i go to run it i get 

```
Traceback (most recent call last):
  File "/Users/william/ascii-video-player/src/bad-apple/convert.py", line 1, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
Traceback (most recent call last):
  File "/Users/william/ascii-video-player/src/bad-apple/main.py", line 10, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by Wdboyes13** [comment]
issue fixed

run attached shell file which will install everything for badapple and AVP

then run ` python3 launcher.py `

file at https://github.com/Wdboyes13/coding/blob/main/badapple.sh
